/**
 * Mock nearby businesses for "Ao redor" mode
 */

import type { NearbyBusiness } from '../components/NearbyBusinessCard';

export const MOCK_NEARBY_BUSINESSES: NearbyBusiness[] = [
  {
    id: 'nb-1',
    name: 'Restaurante Pelô Bistrô',
    type: 'restaurante',
    category: 'Comida Baiana',
    distance: '150m',
    description: 'Comida baiana contemporânea com vista para o Pelourinho. Moqueca premiada.',
    rating: 4.6,
    review_count: 340,
    price_range: '$$',
    opening_hours: '11h - 23h',
    is_open: true,
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=300&fit=crop',
    address: 'Rua do Pelourinho, 45',
    neighborhood: 'Pelourinho',
  },
  {
    id: 'nb-2',
    name: 'Café do Terreiro',
    type: 'cafe',
    category: 'Cafeteria',
    distance: '200m',
    description: 'Café artesanal baiano, bolos caseiros e ambiente aconchegante.',
    rating: 4.8,
    review_count: 215,
    price_range: '$',
    opening_hours: '7h - 19h',
    is_open: true,
    image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400&h=300&fit=crop',
    address: 'Terreiro de Jesus, 12',
    neighborhood: 'Centro Histórico',
  },
  {
    id: 'nb-3',
    name: 'Artesanato Bahia',
    type: 'loja',
    category: 'Artesanato',
    distance: '100m',
    description: 'Lembranças, artesanato local, fitinhas do Bonfim e berimbaus artesanais.',
    rating: 4.2,
    review_count: 180,
    price_range: '$',
    opening_hours: '9h - 18h',
    is_open: true,
    image_url: 'https://images.unsplash.com/photo-1528698827591-e625c5e5a5e0?w=400&h=300&fit=crop',
    address: 'Rua das Laranjeiras, 22',
    neighborhood: 'Pelourinho',
  },
  {
    id: 'nb-4',
    name: 'Tour Histórico a Pé',
    type: 'experiencia',
    category: 'Passeio guiado',
    distance: '50m',
    description: 'Passeio guiado pelo centro histórico com guia credenciado. 2h de duração.',
    rating: 4.9,
    review_count: 520,
    price_range: '$$',
    opening_hours: '9h - 17h',
    is_open: true,
    image_url: 'https://images.unsplash.com/photo-1564507004663-b6dfb3c824d5?w=400&h=300&fit=crop',
    address: 'Praça Municipal',
    neighborhood: 'Centro Histórico',
  },
  {
    id: 'nb-5',
    name: 'Bar do Reggae',
    type: 'bar',
    category: 'Bar / Música ao vivo',
    distance: '250m',
    description: 'Reggae ao vivo toda terça. Drinks tropicais e comida de boteco baiana.',
    rating: 4.4,
    review_count: 890,
    price_range: '$',
    opening_hours: '17h - 2h',
    is_open: false,
    image_url: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400&h=300&fit=crop',
    address: 'Ladeira do Pelourinho',
    neighborhood: 'Pelourinho',
  },
  {
    id: 'nb-6',
    name: 'Pousada Colonial',
    type: 'hotel',
    category: 'Pousada',
    distance: '180m',
    description: 'Pousada charmosa em casarão colonial restaurado. Café da manhã incluído.',
    rating: 4.5,
    review_count: 145,
    price_range: '$$$',
    opening_hours: '24h',
    is_open: true,
    image_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=400&h=300&fit=crop',
    address: 'Rua do Carmo, 8',
    neighborhood: 'Centro Histórico',
  },
  {
    id: 'nb-7',
    name: 'Acarajé da Dinha',
    type: 'restaurante',
    category: 'Comida de rua',
    distance: '500m',
    description: 'O acarajé mais famoso de Salvador. Fila que vale a pena.',
    rating: 4.7,
    review_count: 2100,
    price_range: '$',
    opening_hours: '16h - 22h',
    is_open: true,
    image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop',
    address: 'Largo de Santana, Rio Vermelho',
    neighborhood: 'Rio Vermelho',
  },
  {
    id: 'nb-8',
    name: 'Capoeira Experience',
    type: 'experiencia',
    category: 'Aula de capoeira',
    distance: '120m',
    description: 'Aula introdutória de capoeira com mestres locais. Para todos os níveis.',
    rating: 4.8,
    review_count: 310,
    price_range: '$$',
    opening_hours: '10h - 18h',
    is_open: true,
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=300&fit=crop',
    address: 'Forte da Capoeira, Pelourinho',
    neighborhood: 'Pelourinho',
  },
];

export const NEARBY_BUSINESS_TYPES = [
  { key: 'todos', label: 'Todos', emoji: '📍' },
  { key: 'restaurante', label: 'Restaurantes', emoji: '🍽️' },
  { key: 'cafe', label: 'Cafés', emoji: '☕' },
  { key: 'bar', label: 'Bares', emoji: '🍸' },
  { key: 'loja', label: 'Lojas', emoji: '🛍️' },
  { key: 'hotel', label: 'Hospedagem', emoji: '🏨' },
  { key: 'experiencia', label: 'Experiências', emoji: '🎯' },
  { key: 'servico', label: 'Serviços', emoji: '🔧' },
] as const;
