import { useEffect, useState, type ReactNode } from "react";
import { Helmet } from "react-helmet-async";
import { Link, useLocation, useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  CalendarDays,
  CameraOff,
  Check,
  CheckCircle2,
  ChevronRight,
  CircleAlert,
  Info,
  MapPin,
  QrCode,
  RefreshCw,
  ShieldCheck,
  Ticket,
  UserRound,
  UsersRound,
  WifiOff,
  X,
} from "lucide-react";

import eventImage from "@/assets/community-concept-encontro-rua.jpg";
import cameraImage from "@/assets/bairro-vale-pedrinhas.jpg";
import { cn } from "@/shared/utils/cn";

const CHECKIN_PATH = "/inscricoes-checkin";
const CHECKIN_RESET = "[&_p]:!mb-0 [&_h1]:!mb-0 [&_h2]:!mb-0 [&_h3]:!mb-0 [&_button]:!font-sans";
type CheckinView = "registrations" | "credential" | "confirmed" | "offline" | "invalid" | "scanner" | "already";

const event = { title: "Encontro de leitura", date: "19 set. de 2026", time: "15h", place: "Santa Cruz" };

function route(view?: CheckinView) { return `${CHECKIN_PATH}?concept-mock=1${view ? `&view=${view}` : ""}`; }
function getRequestedView(search: string): CheckinView | null {
  const value = new URLSearchParams(search).get("view") as CheckinView | null;
  return value && ["registrations", "credential", "confirmed", "offline", "invalid", "scanner", "already"].includes(value) ? value : null;
}
function Brand({ light = false }: { light?: boolean }) { return <Link to={route()} aria-label="Achegue-se — inscrição e check-in" className={cn("font-heading text-[1.5rem] font-bold tracking-[-0.065em]", light ? "text-white" : "text-territory-brand")}>achegue-se<span className="text-territory-sun">.</span></Link>; }
function Surface({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={cn("rounded-xl border border-territory-border bg-territory-surface", className)}>{children}</section>; }
function Avatar({ letter = "A", className = "" }: { letter?: string; className?: string }) { return <span className={cn("grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#dce8e4] text-territory-brand", className)}><UserRound className="h-5 w-5" /></span>; }
function Status({ children, tone = "green" }: { children: ReactNode; tone?: "green" | "yellow" | "red" }) { return <span className={cn("inline-flex rounded-full px-3 py-1 text-xs font-semibold", tone === "green" && "bg-[#c8f2de] text-[#126443]", tone === "yellow" && "bg-[#fff0c0] text-[#775400]", tone === "red" && "bg-[#ffe0dc] text-[#9c201b]")}>{children}</span>; }

function MobileHeader({ title, onBack, right }: { title: string; onBack: () => void; right?: ReactNode }) { return <header className="flex min-h-14 items-center gap-2 border-b border-territory-border bg-territory-surface px-4"><button type="button" onClick={onBack} aria-label="Voltar" className="-ml-2 rounded-lg p-2 text-territory-brand"><ArrowLeft className="h-5 w-5" /></button><h1 className="min-w-0 flex-1 truncate text-sm font-bold">{title}</h1>{right}</header>; }

function EventRow({ previous = false, onView }: { previous?: boolean; onView: (view: CheckinView) => void }) { return <Surface className="p-3"><div className="flex gap-3"><img src={previous ? cameraImage : eventImage} alt="" className="h-[7rem] w-[5.4rem] shrink-0 rounded-xl object-cover" /><div className="min-w-0 flex-1"><h2 className="text-base font-bold">{previous ? "Oficina de fotografia" : event.title}</h2><p className="mt-2 flex items-center gap-1 text-xs text-territory-muted"><CalendarDays className="h-3.5 w-3.5" />{previous ? "26 set. · 14h" : "19 set. de 2026 · 15h"}</p><p className="mt-1 flex items-center gap-1 text-xs text-territory-muted"><MapPin className="h-3.5 w-3.5" />{event.place}</p><Status><Check className="mr-1 inline h-3.5 w-3.5" />Confirmada</Status></div></div><button type="button" onClick={() => onView("credential")} className="mt-3 flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-territory-brand text-sm font-bold text-white">{previous ? "Ver inscrição" : "Ver credencial"}<ChevronRight className="h-4 w-4" /></button></Surface>; }

function MobileRegistrations({ onView }: { onView: (view: CheckinView) => void }) { return <div className={cn("min-h-[100dvh] bg-territory-canvas text-territory-ink", CHECKIN_RESET)}><header className="flex items-center justify-between px-4 pb-3 pt-5"><div><h1 className="font-heading text-[1.55rem] font-bold">Minhas inscrições</h1></div><Avatar /></header><main className="px-4 pb-6"><Surface className="flex items-center gap-3 bg-territory-surface p-3"><Avatar /><span className="min-w-0 flex-1"><b className="block text-sm">Ana Oliveira</b><span className="text-xs text-territory-muted">Pessoal</span></span><ChevronRight className="h-5 w-5 text-territory-muted" /></Surface><div className="mt-4 grid grid-cols-2 border-b border-territory-border text-sm"><button type="button" className="min-h-11 border-b-2 border-territory-brand font-bold">Próximos</button><button type="button" className="min-h-11 text-territory-muted">Anteriores</button></div><div className="space-y-3 py-4"><EventRow onView={onView} /><EventRow previous onView={onView} /></div><div className="flex items-start gap-2 rounded-xl bg-[#f0f2f1] p-3 text-xs text-territory-muted"><Info className="mt-0.5 h-4 w-4 shrink-0" />Salvar evento não confirma inscrição.</div></main></div>; }

function CredentialCard({ onView }: { onView: (view: CheckinView) => void }) { return <Surface className="p-4"><h2 className="font-heading text-xl font-bold">{event.title}</h2><p className="mt-3 flex items-center gap-2 text-sm text-territory-muted"><CalendarDays className="h-4 w-4" />{event.date} · {event.time}</p><p className="mt-2 flex items-center gap-2 text-sm text-territory-muted"><MapPin className="h-4 w-4" />{event.place}</p><hr className="my-4 border-territory-border" /><div className="flex items-center gap-3"><Avatar /><span><b className="block text-sm">Ana Oliveira</b><span className="text-xs text-territory-muted">Pessoal</span></span></div><div className="relative mx-auto mt-5 grid h-48 w-48 place-items-center overflow-hidden rounded-lg border-8 border-white bg-[#eff3f2] shadow-inner"><QrCode className="h-36 w-36 text-territory-brand" /><span className="absolute rotate-[-14deg] bg-territory-sun px-3 py-1 text-sm font-bold tracking-wide">DEMONSTRATIVO</span></div><p className="mt-3 text-center text-sm">Apresente à equipe na entrada.</p><div className="mt-2 rounded-lg bg-territory-raised px-3 py-2 text-center text-sm">Código: <b>EXEMPLO</b></div><div className="mt-3 flex items-center gap-2 rounded-lg bg-[#ddf3e2] p-3 text-sm"><CheckCircle2 className="h-5 w-5 text-[#21804e]" />Inscrição confirmada</div><button type="button" onClick={() => onView("credential")} className="mt-3 flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-territory-brand text-sm font-bold text-white"><RefreshCw className="h-4 w-4" />Atualizar credencial</button><button type="button" className="mt-2 flex min-h-11 w-full items-center justify-center gap-2 rounded-lg border border-territory-brand text-sm font-semibold">Ver evento<ChevronRight className="h-4 w-4" /></button></Surface>; }
function MobileCredential({ onView }: { onView: (view: CheckinView) => void }) { return <div className={cn("min-h-[100dvh] bg-territory-canvas text-territory-ink", CHECKIN_RESET)}><MobileHeader title="Minha credencial" onBack={() => onView("registrations")} /><main className="px-4 pb-5 pt-4"><CredentialCard onView={onView} /><div className="mt-3 flex items-start gap-2 rounded-xl bg-[#f0f2f1] p-3 text-xs text-territory-muted"><Info className="mt-0.5 h-4 w-4 shrink-0" />A entrada só é confirmada após validação.</div></main></div>; }

function MobileConfirmed({ onView }: { onView: (view: CheckinView) => void }) { return <div className={cn("min-h-[100dvh] bg-territory-surface text-territory-ink", CHECKIN_RESET)}><main className="px-4 pb-6 pt-12 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#2b8a55] text-white"><Check className="h-9 w-9" strokeWidth={3} /></span><h1 className="mt-5 font-heading text-[1.4rem] font-bold">Presença confirmada</h1><p className="mt-1 text-sm text-territory-muted">Sua entrada foi registrada no evento.</p><hr className="my-5 border-territory-border" /><div className="text-left"><h2 className="font-heading text-lg font-bold">{event.title}</h2><p className="mt-2 flex items-center gap-2 text-sm text-territory-muted"><CalendarDays className="h-4 w-4" />{event.date} · 15h05</p><p className="mt-2 flex items-center gap-2 text-sm text-territory-muted"><MapPin className="h-4 w-4" />{event.place}</p><hr className="my-4 border-territory-border" /><div className="flex items-center gap-3"><Avatar /><span><b className="block text-sm">Ana Oliveira</b><span className="text-xs text-territory-muted">Pessoal</span></span></div></div><div className="mt-4 flex items-start gap-2 rounded-xl bg-[#ddf3e2] p-3 text-left text-xs text-[#216a43]"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0" /><span><b className="block">Registro confirmado pelo servidor</b>Sua presença no evento foi registrada com sucesso.</span></div><button type="button" onClick={() => onView("registrations")} className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-territory-brand text-sm font-bold text-white">Ver evento<ChevronRight className="h-4 w-4" /></button><button type="button" className="mt-2 flex min-h-11 w-full items-center justify-center gap-2 rounded-lg border border-territory-brand text-sm font-semibold"><Ticket className="h-4 w-4" />Ver registro</button><Surface className="mt-4 bg-[#fff5dc] p-4 text-left"><b className="block text-sm">Certificado</b><p className="mt-1 text-xs text-territory-muted">Quando oferecido pelo organizador e conforme os critérios do evento.</p></Surface></main></div>; }

function MobileOffline({ onView }: { onView: (view: CheckinView) => void }) { return <div className={cn("min-h-[100dvh] bg-territory-surface text-territory-ink", CHECKIN_RESET)}><MobileHeader title="Minha credencial" onBack={() => onView("registrations")} /><main className="px-4 pb-6 pt-20 text-center"><WifiOff className="mx-auto h-20 w-20 text-territory-muted" /><h1 className="mt-8 font-heading text-2xl font-bold">Não foi possível atualizar</h1><p className="mt-2 text-sm leading-5 text-territory-muted">Não conseguimos consultar a situação da sua inscrição.</p><Surface className="mt-5 flex items-center gap-3 bg-territory-raised p-4 text-left"><CalendarDays className="h-6 w-6 text-territory-brand" /><b className="text-sm">{event.title}</b></Surface><div className="mt-4 flex items-start gap-2 rounded-xl bg-[#fff1d1] p-4 text-left text-xs text-[#745300]"><Info className="h-4 w-4 shrink-0" />Não é possível confirmar o resultado sem consultar o servidor.</div><button type="button" onClick={() => onView("credential")} className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-territory-brand text-sm font-bold text-white"><RefreshCw className="h-4 w-4" />Tentar novamente</button><button type="button" className="mt-2 flex min-h-11 w-full items-center justify-center gap-2 rounded-lg border border-territory-brand text-sm font-semibold"><UsersRound className="h-4 w-4" />Procurar a equipe</button></main></div>; }

function ScannerPanel({ onView }: { onView: (view: CheckinView) => void }) { return <Surface className="p-6"><h2 className="font-heading text-2xl font-bold">Ler credencial</h2><div className="relative mt-4 grid min-h-60 place-items-center rounded-lg border border-territory-border bg-[#f1f3f2] text-center"><div className="pointer-events-none absolute inset-x-[31%] inset-y-[10%]"><span className="absolute left-0 top-0 h-8 w-8 rounded-tl-md border-l-4 border-t-4 border-territory-brand" /><span className="absolute right-0 top-0 h-8 w-8 rounded-tr-md border-r-4 border-t-4 border-territory-brand" /><span className="absolute bottom-0 left-0 h-8 w-8 rounded-bl-md border-b-4 border-l-4 border-territory-brand" /><span className="absolute bottom-0 right-0 h-8 w-8 rounded-br-md border-b-4 border-r-4 border-territory-brand" /></div><div><CameraOff className="mx-auto h-14 w-14 text-territory-muted" /><b className="mt-2 block text-sm text-territory-muted">CÂMERA DESATIVADA</b><button type="button" className="mt-4 min-h-10 rounded-lg bg-territory-brand px-5 text-sm font-bold text-white">Ativar câmera</button><p className="mt-2 text-xs text-territory-muted">A leitura exige permissão de câmera.</p></div></div><div className="my-4 flex items-center gap-3 text-sm text-territory-muted"><span className="h-px flex-1 bg-territory-border" />Ou informar código<span className="h-px flex-1 bg-territory-border" /></div><div className="flex gap-3"><input aria-label="Código da credencial" placeholder="Digite o código da credencial" className="min-h-11 min-w-0 flex-1 rounded-lg border border-territory-border px-3 text-sm" /><button type="button" onClick={() => onView("confirmed")} className="min-h-11 rounded-lg bg-territory-brand px-5 text-sm font-bold text-white">Validar código</button></div></Surface>; }

function DesktopTopbar() { return <header className="flex min-h-[4.25rem] items-center justify-between bg-territory-brand px-11 text-white"><div className="flex items-center gap-5"><Brand light /><span className="h-7 w-px bg-white/50" /><span className="text-sm">Encontro de leitura</span></div><div className="flex items-center gap-3 text-sm">Ana · Equipe autorizada<Avatar className="bg-white text-territory-brand" /></div></header>; }
function DesktopShell({ onView }: { onView: (view: CheckinView) => void }) { return <div className={cn("hidden min-h-[100dvh] bg-territory-canvas text-territory-ink lg:block", CHECKIN_RESET)}><DesktopTopbar /><main className="px-11 pb-8 pt-4"><h1 className="font-heading text-[2.5rem] font-bold leading-[1.1] tracking-[-0.05em]">Validar entrada</h1><p className="mt-1 text-[1.5rem] leading-[1.2] text-territory-muted">{event.date} · {event.place}</p><div className="mt-5 flex gap-8 border-b border-territory-border text-base"><button type="button" className="border-b-2 border-territory-brand pb-3 font-bold">Validar código</button><button type="button" className="pb-3 text-territory-muted">Participantes</button><button type="button" className="pb-3 text-territory-muted">Histórico</button></div><div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(20rem,1fr)]"><ScannerPanel onView={onView} /><Surface className="p-6"><h2 className="font-heading text-2xl font-bold">Confira o evento antes de validar</h2><div className="mt-5 flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-full bg-territory-sun text-territory-brand"><CalendarDays className="h-6 w-6" /></span><div><b className="block text-base">{event.title}</b><span className="text-sm text-territory-muted">{event.date} · {event.place}</span></div></div><hr className="my-5 border-territory-border" /><p className="flex items-center gap-3 text-sm"><ShieldCheck className="h-5 w-5 text-territory-brand" />Somente a equipe autorizada registra entradas.</p><p className="mt-5 flex items-center gap-3 text-sm"><RefreshCw className="h-5 w-5 text-territory-brand" />Aguarde a confirmação do servidor.</p><hr className="my-5 border-territory-border" /><div className="flex gap-7 text-sm font-semibold text-[#176a6e]"><button type="button" className="flex items-center gap-2"><UsersRound className="h-5 w-5" />Ver participantes →</button><button type="button" className="flex items-center gap-2"><RefreshCw className="h-5 w-5" />Atualizar lista</button></div><hr className="my-5 border-territory-border" /><p className="flex items-center gap-2 text-xs text-territory-muted"><Info className="h-4 w-4" />Busca por nome não substitui validação da entrada.</p></Surface></div><ValidationResults onView={onView} /></main></div>; }
function ValidationResults({ onView }: { onView: (view: CheckinView) => void }) { return <section className="mt-7 border-t border-territory-border pt-5"><h2 className="font-heading text-2xl font-bold">Resultados da validação</h2><div className="mt-4 grid gap-4 xl:grid-cols-3"><Surface className="border-[#92d7af] bg-[#ecfaf1] p-5"><div className="flex items-start gap-3"><span className="grid h-12 w-12 place-items-center rounded-full bg-[#2b9360] text-white"><Check className="h-7 w-7" /></span><div><h3 className="text-lg font-bold text-[#146440]">Entrada confirmada</h3><b className="block">Ana Oliveira</b><p className="text-sm">{event.title} · 15h05</p><p className="mt-2 text-sm">Registro concluído.</p></div></div><button type="button" onClick={() => onView("confirmed")} className="mt-5 min-h-11 w-full rounded-lg bg-territory-brand text-sm font-bold text-white">Próxima credencial</button></Surface><Surface className="border-[#efd99a] bg-[#fff8e8] p-5"><div className="flex items-start gap-3"><span className="grid h-12 w-12 place-items-center rounded-full bg-territory-sun text-territory-brand"><CircleAlert className="h-7 w-7" /></span><div><h3 className="text-lg font-bold">Entrada já registrada</h3><b className="block">Rafael Lima</b><p className="text-sm">Registrada às 15h02.</p><p className="mt-2 text-sm">Nenhum novo registro foi criado.</p></div></div><div className="mt-5 grid grid-cols-2 gap-2"><button type="button" onClick={() => onView("already")} className="min-h-11 rounded-lg border border-territory-brand text-sm font-semibold">Ver registro</button><button type="button" className="min-h-11 rounded-lg bg-territory-brand text-sm font-bold text-white">Próxima credencial</button></div></Surface><Surface className="border-[#ffbbb5] bg-[#fff0ef] p-5"><div className="flex items-start gap-3"><span className="grid h-12 w-12 place-items-center rounded-full bg-[#df3030] text-white"><X className="h-7 w-7" /></span><div><h3 className="text-lg font-bold text-[#c51f1b]">Credencial não validada</h3><p className="mt-2 text-sm">Confira o código e o evento selecionado.</p><p className="mt-2 text-sm">Não confirme a entrada sem validação.</p></div></div><div className="mt-5 grid grid-cols-2 gap-2"><button type="button" onClick={() => onView("invalid")} className="min-h-11 rounded-lg bg-territory-brand text-sm font-bold text-white">Tentar novamente</button><button type="button" className="min-h-11 rounded-lg border border-territory-brand text-sm font-semibold">Voltar</button></div></Surface></div></section>; }

function MobileState({ view, onView }: { view: "invalid" | "already"; onView: (view: CheckinView) => void }) { const invalid = view === "invalid"; return <div className={cn("min-h-[100dvh] bg-territory-canvas px-4 pb-6 text-territory-ink", CHECKIN_RESET)}><MobileHeader title="Validar entrada" onBack={() => onView("registrations")} /><Surface className={cn("mt-8 p-5 text-center", invalid ? "border-[#ffbbb5]" : "border-[#efd99a]")}><span className={cn("mx-auto grid h-14 w-14 place-items-center rounded-full", invalid ? "bg-[#ffe0dc] text-[#bd201c]" : "bg-[#fff0c0] text-[#805500]")}>{invalid ? <X className="h-7 w-7" /> : <CircleAlert className="h-7 w-7" />}</span><h1 className="mt-4 font-heading text-xl font-bold">{invalid ? "Credencial não validada" : "Entrada já registrada"}</h1><p className="mt-2 text-sm text-territory-muted">{invalid ? "Confira o código e o evento selecionado." : "Nenhum novo registro foi criado."}</p><button type="button" onClick={() => onView("registrations")} className="mt-5 min-h-11 w-full rounded-lg bg-territory-brand text-sm font-bold text-white">{invalid ? "Tentar novamente" : "Ver registro"}</button></Surface></div>; }

export default function InscricaoCheckinConceptMockPage() { const location = useLocation(); const navigate = useNavigate(); const [isDesktop, setIsDesktop] = useState(() => typeof window !== "undefined" && window.innerWidth >= 1024); const [view, setView] = useState<CheckinView>(getRequestedView(location.search) ?? "registrations"); useEffect(() => { const onResize = () => setIsDesktop(window.innerWidth >= 1024); window.addEventListener("resize", onResize); return () => window.removeEventListener("resize", onResize); }, []); useEffect(() => { setView(getRequestedView(location.search) ?? "registrations"); }, [location.search]); const onView = (next: CheckinView) => { setView(next); navigate(route(next), { replace: true }); }; let mobile: ReactNode; if (view === "registrations") mobile = <MobileRegistrations onView={onView} />; else if (view === "credential") mobile = <MobileCredential onView={onView} />; else if (view === "confirmed") mobile = <MobileConfirmed onView={onView} />; else if (view === "offline") mobile = <MobileOffline onView={onView} />; else if (view === "invalid" || view === "already") mobile = <MobileState view={view} onView={onView} />; else mobile = <MobileRegistrations onView={onView} />; return <><Helmet><title>Minhas inscrições | Achegue-se</title><meta name="robots" content="noindex, nofollow" /></Helmet>{isDesktop ? <DesktopShell onView={onView} /> : mobile}</>; }
