import { useEffect, useState, type ReactNode } from "react";
import { Helmet } from "react-helmet-async";
import { Link, useLocation, useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  ArrowRight,
  Bell,
  Check,
  ChevronRight,
  CircleAlert,
  CircleDollarSign,
  Edit3,
  Ellipsis,
  Eye,
  Home,
  ImagePlus,
  Images,
  Info,
  ListChecks,
  MapPin,
  MessageCircle,
  MoreHorizontal,
  Plus,
  Search,
  Settings,
  Shield,
  Tag,
  UserRound,
  UsersRound,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

import listingImage from "@/assets/community-concept-encontro-rua.jpg";
import listingImageAlt from "@/assets/bairro-vale-pedrinhas.jpg";
import { cn } from "@/shared/utils/cn";

const ADS_PATH = "/meus-anuncios";
const RESET = "[&_p]:!mb-0 [&_h1]:!mb-0 [&_h2]:!mb-0 [&_h3]:!mb-0 [&_button]:!font-sans";
type AdView = "info" | "photos" | "review" | "manage" | "contact" | "sell" | "error";
const ad = { title: "Bicicleta aro 26", price: "R$ 350", place: "Santa Cruz · Salvador" };
const summaryItems: Array<{ label: string; Icon: LucideIcon }> = [
  { label: "Informações", Icon: Info },
  { label: "Preço", Icon: CircleDollarSign },
  { label: "Localização", Icon: MapPin },
  { label: "Fotos", Icon: Images },
  { label: "Detalhes", Icon: ListChecks },
  { label: "Contato", Icon: MessageCircle },
  { label: "Disponibilidade", Icon: Eye },
];

function route(view?: AdView) { return `${ADS_PATH}?concept-mock=1${view && view !== "info" ? `&view=${view}` : ""}`; }
function requested(search: string): AdView { const value = new URLSearchParams(search).get("view") as AdView | null; return value && ["info", "photos", "review", "manage", "contact", "sell", "error"].includes(value) ? value : "info"; }
function Brand({ light = false }: { light?: boolean }) { return <Link to={route()} aria-label="Achegue-se — meus anúncios" className={cn("font-heading text-[1.65rem] font-bold tracking-[-0.065em]", light ? "text-white" : "text-territory-brand")}>achegue-se<span className="text-territory-sun">.</span></Link>; }
function Surface({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={cn("rounded-xl border border-territory-border bg-territory-surface", className)}>{children}</section>; }
function Avatar() { return <span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#dce8e4] text-territory-brand"><UserRound className="h-5 w-5" /></span>; }
function Stepper({ active }: { active: number }) { return <div className="relative flex items-center justify-between" aria-label={`Etapa ${active} de 8`}><span aria-hidden="true" className="absolute inset-x-1 top-1/2 h-px -translate-y-1/2 bg-[#dfe5e3]" />{Array.from({ length: 8 }, (_, index) => <span key={index} className={cn("relative z-[1] h-3 w-3 rounded-full ring-4 ring-territory-canvas", index < active ? "bg-territory-sun" : "bg-[#dfe5e3]")} />)}</div>; }
function MobileHeader({ title, onBack, close = false }: { title: string; onBack: () => void; close?: boolean }) { return <header className="flex min-h-14 items-center justify-between border-b border-territory-border bg-territory-surface px-4"><button type="button" onClick={onBack} aria-label="Voltar" className="rounded-lg p-2 text-territory-brand"><ArrowLeft className="h-5 w-5" /></button><h1 className="text-base font-bold">{title}</h1><button type="button" aria-label={close ? "Fechar" : "Configurações"} className="rounded-lg p-2 text-territory-brand">{close ? <X className="h-5 w-5" /> : <Settings className="h-5 w-5" />}</button></header>; }
function MobileNav({ onView }: { onView: (view: AdView) => void }) { return <nav className="fixed inset-x-0 bottom-0 z-20 grid grid-cols-5 border-t border-territory-border bg-territory-surface pb-[env(safe-area-inset-bottom)] shadow-[0_-4px_14px_rgba(8,48,49,0.08)]" aria-label="Navegação principal"><button type="button" className="flex min-h-14 flex-col items-center justify-center gap-1 text-[10px] text-territory-muted"><Home className="h-5 w-5" />Início</button><button type="button" className="flex min-h-14 flex-col items-center justify-center gap-1 text-[10px] text-territory-muted"><UsersRound className="h-5 w-5" />Comunidade</button><button type="button" onClick={() => onView("info")} className="-mt-4 flex h-14 w-14 self-start items-center justify-center justify-self-center rounded-full border-4 border-territory-surface bg-territory-sun text-territory-brand shadow-md" aria-label="Publicar"><Plus className="h-6 w-6" /></button><button type="button" className="flex min-h-14 flex-col items-center justify-center gap-1 text-[10px] text-territory-muted"><MessageCircle className="h-5 w-5" />Conversas</button><button type="button" onClick={() => onView("manage")} className="flex min-h-14 flex-col items-center justify-center gap-1 text-[10px] font-bold text-territory-brand"><UserRound className="h-5 w-5" />Conta</button></nav>; }
function Field({ label, value, counter, placeholder }: { label: string; value?: string; counter?: string; placeholder?: string }) { return <label className="block text-sm font-semibold">{label}<div className="relative mt-2"><input defaultValue={value} placeholder={placeholder} className="min-h-11 w-full rounded-lg border border-territory-border bg-white px-3 font-normal outline-none placeholder:text-territory-muted" />{counter && <span className="absolute bottom-[-1.15rem] right-0 text-[11px] font-normal text-territory-muted">{counter}</span>}</div></label>; }
function SelectField({ label, value }: { label: string; value: string }) { return <label className="mt-6 block text-sm font-semibold">{label}<div className="mt-2 flex min-h-11 items-center justify-between rounded-lg border border-territory-border bg-white px-3 font-normal">{value}<ChevronRight className="h-4 w-4 text-territory-muted" /></div></label>; }
function MobileInfo({ onView }: { onView: (view: AdView) => void }) { return <div className={cn("min-h-[100dvh] bg-territory-canvas text-territory-ink", RESET)}><MobileHeader title="Novo anúncio" onBack={() => onView("manage")} close /><main className="px-4 pb-24 pt-5"><div className="flex items-center gap-3"><Avatar /><p className="text-sm">Publicando como <b>Ana Oliveira</b><span className="ml-2 inline-flex rounded-md bg-[#eef1ef] px-2 py-1 text-xs">Pessoal⌄</span></p></div><div className="mt-6"><Stepper active={1} /><p className="mt-3 text-xs text-territory-muted">Etapa 1 de 8</p></div><div className="mt-6 space-y-6"><Field label="Título do anúncio" value={ad.title} counter="17/100" /><SelectField label="Categoria" value="Esportes" /><SelectField label="Subcategoria" value="Bicicletas" /><SelectField label="Condição" value="Usado" /><label className="block text-sm font-semibold">Descrição<textarea defaultValue="Bicicleta revisada. Retirada a combinar." className="mt-2 min-h-24 w-full resize-none rounded-lg border border-territory-border bg-white p-3 font-normal" /><span className="mt-1 block text-right text-[11px] font-normal text-territory-muted">37/2000</span></label></div><button type="button" onClick={() => onView("photos")} className="mt-6 flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-territory-sun font-bold">Continuar<ArrowRight className="h-4 w-4" /></button><button type="button" className="mt-2 flex min-h-11 w-full items-center justify-center gap-2 rounded-lg border border-territory-brand text-sm font-semibold">Salvar rascunho</button><p className="mt-3 text-center text-xs text-territory-muted"><Info className="mr-1 inline h-3.5 w-3.5" />Rascunho recuperável depende de implementação.</p></main><MobileNav onView={onView} /></div>; }
function MobilePhotos({ onView }: { onView: (view: AdView) => void }) { return <div className={cn("min-h-[100dvh] bg-territory-canvas text-territory-ink", RESET)}><MobileHeader title="Novo anúncio" onBack={() => onView("info")} close /><main className="px-4 pb-24 pt-5"><Stepper active={4} /><div className="mt-3 flex justify-between text-xs text-territory-muted"><span>Etapa 4 de 8</span><b className="text-territory-ink">3 de 10 fotos</b></div><h1 className="mt-6 font-heading text-2xl font-bold">Fotos do produto</h1><p className="mt-1 text-sm text-territory-muted">Adicione fotos nítidas e de diferentes ângulos.</p><div className="mt-5 grid grid-cols-2 gap-2"><div className="relative"><img src={listingImage} alt="Foto demonstrativa da bicicleta" className="h-44 w-full rounded-xl object-cover" /><span className="absolute left-2 top-2 rounded bg-territory-sun px-2 py-1 text-xs font-bold">Capa</span><button type="button" aria-label="Opções da foto" className="absolute right-2 top-2 rounded-full bg-white p-1"><MoreHorizontal className="h-4 w-4" /></button></div><img src={listingImageAlt} alt="Foto demonstrativa" className="h-44 w-full rounded-xl object-cover" /><img src={listingImage} alt="Foto demonstrativa" className="h-44 w-full rounded-xl object-cover" /><button type="button" className="grid h-44 place-items-center rounded-xl border border-dashed border-territory-brand text-center"><ImagePlus className="mx-auto h-7 w-7" /><span className="mt-2 block text-xs">Adicionar foto</span></button></div><div className="mt-5 flex items-center gap-2 rounded-xl bg-[#eef1ef] p-3 text-xs text-territory-muted"><Info className="h-4 w-4 shrink-0" />Mostre o estado real do produto.</div><div className="mt-20 flex gap-2"><button type="button" onClick={() => onView("info")} className="min-h-11 flex-1 rounded-lg border border-territory-brand font-semibold">Voltar</button><button type="button" onClick={() => onView("review")} className="min-h-11 flex-1 rounded-lg bg-territory-sun font-bold">Continuar</button></div></main></div>; }
function ReviewSummary({ onView }: { onView: (view: AdView) => void }) { return <div className={cn("min-h-[100dvh] bg-territory-canvas text-territory-ink", RESET)}><MobileHeader title="Novo anúncio" onBack={() => onView("photos")} close /><main className="px-4 pb-7 pt-5"><Stepper active={8} /><p className="mt-3 text-xs text-territory-muted">Etapa 8 de 8</p><h1 className="mt-6 font-heading text-2xl font-bold">Confira seu anúncio</h1><p className="mt-1 text-sm text-territory-muted">Tudo certo? Revise as informações antes de publicar.</p><Surface className="mt-4 flex items-center gap-3 p-3"><img src={listingImage} alt="Foto demonstrativa" className="h-20 w-20 rounded-lg object-cover" /><div><b className="block">{ad.title}</b><b className="block text-lg">{ad.price}</b><span className="block text-xs text-territory-muted">Usado · Esportes · Bicicletas</span><span className="mt-1 flex items-center gap-1 text-xs text-territory-muted"><MapPin className="h-3.5 w-3.5" />{ad.place}</span></div></Surface><h2 className="mt-5 font-heading text-lg font-bold">Resumo</h2><div className="mt-2 divide-y divide-territory-border border-y border-territory-border">{summaryItems.map(({ label, Icon }) => <button type="button" key={label} className="flex min-h-12 w-full items-center gap-3 text-sm"><Icon className="h-4 w-4 shrink-0 text-territory-brand" />{label}<span className="ml-auto text-right text-territory-muted">{label === "Fotos" ? "3 fotos" : label === "Localização" ? ad.place : label === "Disponibilidade" ? "Comunidade" : ""}</span><Edit3 className="h-4 w-4 shrink-0 text-territory-brand" /></button>)}</div><div className="mt-4 flex items-start gap-2 rounded-xl bg-[#eef1ef] p-3 text-xs text-territory-muted"><Info className="h-4 w-4 shrink-0" />Confira quais contatos ficarão visíveis.</div><button type="button" className="mt-5 min-h-11 w-full rounded-lg bg-territory-sun font-bold">Enviar anúncio</button><p className="mt-2 text-center text-xs text-territory-muted">A resposta do servidor determina publicado ou em análise.</p></main></div>; }
function Status({ children, tone }: { children: ReactNode; tone: "green" | "yellow" | "gray" }) { return <span className={cn("rounded-full px-2 py-1 text-xs font-semibold", tone === "green" && "bg-[#d8f2df] text-[#176a42]", tone === "yellow" && "bg-[#fff0bd] text-[#745300]", tone === "gray" && "bg-[#e6ebea] text-[#566260]")}>{children}</span>; }
function AdRow({ name, price, place, status, tone, image = listingImage, onView }: { name: string; price: string; place: string; status: string; tone: "green" | "yellow" | "gray"; image?: string; onView: (view: AdView) => void }) { return <Surface className="p-3"><div className="flex gap-3"><img src={image} alt="Imagem demonstrativa" className="h-20 w-20 rounded-lg object-cover" /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><b className="block text-sm">{name}</b><b className="block text-lg">{price}</b></div><Status tone={tone}>{status}</Status></div><p className="mt-1 flex items-center gap-1 text-xs text-territory-muted"><MapPin className="h-3.5 w-3.5" />{place}</p></div></div><div className="mt-3 flex gap-2"><button type="button" onClick={() => onView("info")} className="min-h-9 flex-1 rounded-lg border border-territory-border text-xs font-semibold">Editar</button><button type="button" onClick={() => onView(status === "Pausado" ? "manage" : "sell")} className="min-h-9 flex-1 rounded-lg border border-territory-border text-xs font-semibold">{status === "Pausado" ? "Reativar" : status === "Ativo" ? "Marcar vendido" : "Ver situação"}</button><button type="button" aria-label="Mais ações" className="grid h-9 w-9 place-items-center"><Ellipsis className="h-4 w-4" /></button></div></Surface>; }
function MobileManage({ onView }: { onView: (view: AdView) => void }) { return <div className={cn("min-h-[100dvh] bg-territory-canvas text-territory-ink", RESET)}><header className="flex items-center justify-between px-4 pb-3 pt-5"><div><h1 className="font-heading text-2xl font-bold">Meus anúncios</h1><p className="mt-1 text-sm text-territory-muted">Ana Oliveira</p></div><Settings className="h-5 w-5 text-territory-brand" /></header><main className="px-4 pb-20"><div className="flex items-center gap-3"><Avatar /><p className="min-w-0 flex-1 text-sm"><b className="block">Ana Oliveira</b><span className="text-xs text-territory-muted">Anúncios aproximam histórias.</span></p></div><button type="button" onClick={() => onView("info")} className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-territory-sun font-bold"><Plus className="h-5 w-5" />Novo anúncio</button><label className="mt-3 flex min-h-11 items-center gap-2 rounded-xl bg-[#eef1ef] px-3 text-sm text-territory-muted"><Search className="h-5 w-5" /><input aria-label="Buscar meus anúncios" placeholder="Buscar meus anúncios" className="min-w-0 flex-1 bg-transparent outline-none" /></label><div className="mt-4 flex gap-2 overflow-x-auto pb-1 text-xs"><button type="button" className="rounded-full bg-territory-brand px-4 py-2 font-bold text-white">Todos</button><button type="button" className="rounded-full bg-[#eef1ef] px-4 py-2">Ativos</button><button type="button" className="rounded-full bg-[#eef1ef] px-4 py-2">Em análise</button><button type="button" className="rounded-full bg-[#eef1ef] px-4 py-2">Pausados</button></div><div className="mt-4 space-y-3"><AdRow name={ad.title} price={ad.price} place={ad.place} status="Ativo" tone="green" onView={onView} /><AdRow name="Mesa de madeira" price="R$ 180" place="Chapada · Salvador" status="Em análise" tone="yellow" image={listingImageAlt} onView={onView} /><AdRow name="Cadeira de jantar" price="R$ 90" place="Santa Cruz · Salvador" status="Pausado" tone="gray" image={listingImageAlt} onView={onView} /></div></main><MobileNav onView={onView} /></div>; }
function MobileState({ view, onView }: { view: "sell" | "error"; onView: (view: AdView) => void }) { const error = view === "error"; return <div className={cn("min-h-[100dvh] bg-territory-canvas px-4 text-territory-ink", RESET)}><MobileHeader title={error ? "Envio não concluído" : "Marcar como vendido?"} onBack={() => onView("manage")} /><Surface className="mt-16 p-6 text-center"><span className={cn("mx-auto grid h-14 w-14 place-items-center rounded-full", error ? "bg-[#ffe0dc] text-[#c5201c]" : "bg-[#fff0bd] text-territory-brand")}>{error ? <CircleAlert className="h-7 w-7" /> : <Tag className="h-7 w-7" />}</span><h1 className="mt-4 font-heading text-xl font-bold">{error ? "Envio não concluído" : "Marcar como vendido?"}</h1><p className="mt-2 text-sm text-territory-muted">{error ? "Não foi possível confirmar o envio. Confira a situação antes de tentar novamente." : "O anúncio sairá dos resultados disponíveis. As conversas anteriores permanecem."}</p><button type="button" onClick={() => onView("manage")} className="mt-5 min-h-11 w-full rounded-lg bg-territory-sun font-bold">{error ? "Ver meus anúncios" : "Confirmar vendido"}</button></Surface></div>; }
function DesktopTopbar() { return <header className="flex min-h-[4.25rem] items-center justify-between bg-territory-surface px-10 text-territory-ink"><div className="flex items-center gap-6"><Brand /><span className="h-7 w-px bg-territory-border" /><span className="flex items-center gap-2 text-sm"><MapPin className="h-4 w-4 text-territory-brand" />Complexo do Nordeste de Amaralina</span></div><div className="flex items-center gap-3 text-sm"><span className="grid h-9 w-9 place-items-center rounded-full bg-territory-brand text-xs text-white">AO</span><span><b className="block">Ana Oliveira</b><span className="text-xs text-territory-muted">Pessoal</span></span><ChevronRight className="h-4 w-4 rotate-90" /></div></header>; }
function DesktopRail() { return <aside className="border-r border-territory-border bg-territory-surface px-8 py-7"><h1 className="font-heading text-2xl font-bold">Editar anúncio</h1><nav className="mt-6 space-y-2">{["Informações", "Preço", "Localização", "Fotos", "Detalhes", "Contato", "Visibilidade", "Revisão"].map((item, index) => <div key={item} className={cn("flex min-h-10 items-center gap-3 rounded-lg px-3 text-sm", index === 5 && "bg-[#e5f2ee] font-bold")}><span className={cn("grid h-8 w-8 place-items-center rounded-full border", index === 5 ? "border-territory-brand bg-territory-brand text-white" : "border-territory-border")}>{index + 1}</span>{item}</div>)}</nav></aside>; }
function PreviewCard() { return <Surface className="p-4"><span className="inline-flex rounded-full bg-[#d8f2df] px-3 py-1 text-xs font-semibold text-[#176a42]">Prévia pública</span><img src={listingImage} alt="Prévia demonstrativa" className="mt-3 h-44 w-full rounded-lg object-cover" /><h2 className="mt-3 font-heading text-xl font-bold">{ad.title}</h2><b className="block text-xl text-territory-sun">{ad.price}</b><p className="mt-2 flex items-center gap-1 text-sm text-territory-muted"><MapPin className="h-4 w-4" />{ad.place}</p><hr className="my-4 border-territory-border" /><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-full bg-territory-brand text-xs text-white">AO</span><b>Ana Oliveira</b></div><button type="button" className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-territory-brand font-bold text-white"><MessageCircle className="h-5 w-5" />Conversar com anunciante</button></Surface>; }
function DesktopStateCards({ onView }: { onView: (view: AdView) => void }) { return <section className="mt-7 grid gap-4 border-t border-territory-border pt-5 xl:grid-cols-3"><Surface className="p-4"><h2 className="font-heading text-lg font-bold">01 · Meus anúncios</h2><div className="mt-3 space-y-2 text-xs"><div className="flex items-center gap-2"><img src={listingImage} alt="" className="h-10 w-10 rounded object-cover" /><b className="flex-1">Bicicleta aro 26</b><Status tone="green">Ativo</Status></div><div className="flex items-center gap-2"><img src={listingImageAlt} alt="" className="h-10 w-10 rounded object-cover" /><b className="flex-1">Mesa de madeira</b><Status tone="yellow">Em análise</Status></div><div className="flex items-center gap-2"><img src={listingImageAlt} alt="" className="h-10 w-10 rounded object-cover" /><b className="flex-1">Cadeira</b><Status tone="gray">Pausado</Status></div></div><button type="button" onClick={() => onView("manage")} className="mt-4 min-h-10 w-full rounded-lg border border-territory-brand text-sm font-semibold">Ver meus anúncios</button></Surface><Surface className="p-4 text-center"><h2 className="font-heading text-lg font-bold">02 · Marcar como vendido?</h2><Tag className="mx-auto mt-5 h-10 w-10 text-territory-brand" /><p className="mt-3 text-sm text-territory-muted">O anúncio sairá dos resultados disponíveis. As conversas anteriores permanecem.</p><button type="button" onClick={() => onView("sell")} className="mt-4 min-h-10 rounded-lg bg-territory-sun px-5 text-sm font-bold">Confirmar vendido</button></Surface><Surface className="p-4 text-center"><h2 className="font-heading text-lg font-bold">03 · Envio não concluído</h2><CircleAlert className="mx-auto mt-5 h-10 w-10 text-[#c5201c]" /><p className="mt-3 text-sm text-territory-muted">Não foi possível confirmar o envio. Confira a situação antes de tentar novamente.</p><button type="button" onClick={() => onView("error")} className="mt-4 min-h-10 rounded-lg bg-territory-sun px-5 text-sm font-bold">Ver meus anúncios</button></Surface></section>; }
function DesktopShell({ onView }: { onView: (view: AdView) => void }) { return <div className={cn("hidden min-h-[100dvh] bg-territory-canvas text-territory-ink lg:block", RESET)}><DesktopTopbar /><div className="grid min-h-[calc(100dvh-4.25rem)] grid-cols-[15rem_minmax(0,1fr)]"><DesktopRail /><main className="min-w-0 px-10 pb-8 pt-7"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-heading text-3xl font-bold">Como podem falar com você?</h2><p className="mt-1 text-base text-territory-muted">Confira o perfil e os contatos antes de enviar.</p></div></div><div className="grid gap-8 xl:grid-cols-[minmax(0,1fr)_24rem]"><section><div className="space-y-5"><Field label="Telefone (opcional)" placeholder="Ex.: (71) 98765-4321" /><Field label="WhatsApp (opcional)" placeholder="Ex.: (71) 98765-4321" /><label className="flex items-center gap-3 text-sm"><span className="relative h-7 w-12 rounded-full bg-[#dce2e1]"><span className="absolute left-1 top-1 h-5 w-5 rounded-full bg-white shadow" /></span><span><b className="block font-normal">Exibir telefone</b><span className="text-xs text-territory-muted">Mostre apenas os contatos que deseja tornar públicos.</span></span></label><Surface className="flex items-center gap-4 bg-[#eef3f1] p-5"><span className="grid h-12 w-12 place-items-center rounded-full bg-[#d8ece9] text-territory-brand"><MessageCircle className="h-6 w-6" /></span><div><b className="block">Conversa pelo Achegue-se</b><span className="text-sm text-territory-muted">Quando disponível para este perfil.</span></div></Surface></div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={() => onView("info")} className="min-h-11 rounded-lg border border-territory-brand px-6 font-semibold">Voltar</button><button type="button" className="min-h-11 rounded-lg border border-territory-brand px-6 font-semibold">Salvar rascunho</button><button type="button" onClick={() => onView("error")} className="min-h-11 rounded-lg bg-territory-sun px-7 font-bold">Continuar<ArrowRight className="ml-2 inline h-4 w-4" /></button></div></section><aside><PreviewCard /><p className="mt-3 text-right text-xs text-territory-muted">Edição ampliada proposta</p></aside></div><DesktopStateCards onView={onView} /></main></div></div>; }

export default function MeusAnunciosConceptMockPage() { const location = useLocation(); const navigate = useNavigate(); const [isDesktop, setIsDesktop] = useState(() => typeof window !== "undefined" && window.innerWidth >= 1024); const [view, setView] = useState<AdView>(() => requested(location.search)); useEffect(() => { const onResize = () => setIsDesktop(window.innerWidth >= 1024); window.addEventListener("resize", onResize); return () => window.removeEventListener("resize", onResize); }, []); useEffect(() => { setView(requested(location.search)); }, [location.search]); const onView = (next: AdView) => { setView(next); navigate(route(next), { replace: true }); }; let mobile: ReactNode; if (view === "info") mobile = <MobileInfo onView={onView} />; else if (view === "photos") mobile = <MobilePhotos onView={onView} />; else if (view === "review") mobile = <ReviewSummary onView={onView} />; else if (view === "manage") mobile = <MobileManage onView={onView} />; else if (view === "sell" || view === "error") mobile = <MobileState view={view} onView={onView} />; else mobile = <MobileInfo onView={onView} />; return <><Helmet><title>Meus anúncios | Achegue-se</title><meta name="robots" content="noindex, nofollow" /></Helmet>{isDesktop ? <DesktopShell onView={onView} /> : mobile}</>; }
