/** Compatibility bridge. New code must import from `@/modules/community-events`. */
export {
  EventHero,
  EventTickets,
  EventDescription,
  EventSchedule,
  EventCTA,
  EventCard,
  EventSkeleton,
  EventDetailPage,
  EventsListPage,
} from "@/modules/community-events";
export type {
  Event,
  EventType,
  EventStatus,
  EventCategory,
  TicketType,
  TicketStatus,
  EventTicket,
  EventLocation,
  EventOrganizer,
  EventScheduleItem,
  EventGalleryItem,
  EventFAQ,
  EventRegistration,
  EventFilters,
  EventStats,
  EventCTAType,
} from "@/modules/community-events";
