// Game Plan Validator - Valida e completa planos de jogo
// Import type guards and validation utilities
import {
  isOrdaxGameType,
  isGameLoopType,
  isLifecycleSignal,
  isLifecycleState,
  isLifecycleTransition,
  isLifecycleUI,
  isLifecycleControl,
  validateOrdaxGameType,
  validateGameLoopType,
  validateLifecycleSignal,
  filterValidLifecycleStates,
  filterValidLifecycleTransitions,
  filterValidLifecycleUIs,
  filterValidLifecycleControls,
  filterValidLifecycleSignals,
  validateStringParam,
  validateArrayParam,
  safeToLowerCase,
  safeTrim,
  isNonEmptyString
} from "./game-plan-validator-utils.ts";

export type OrdaxGameType = "platformer" | "topdown" | "shooter" | "puzzle" | "racing" | "sports" | "unknown";
export type GameLoopType = "winlose" | "survival" | "objective";
export type LifecycleSignal = "player_health" | "objective_progress" | "timer";
export type LifecycleState = "start" | "playing" | "gameover";
export type LifecycleTransition = "start->playing" | "playing->gameover" | "gameover->restart";
export type LifecycleUI = "hud" | "gameover_screen";
export type LifecycleControl = "start_game" | "restart_game";

export interface GamePlan {
  kind: "GAME_PLAN";
  gameType: OrdaxGameType;
  title: string;
  description: string;
  coreLoop: string;
  requiredSystems: string[];
  requiredEntities: string[];
  loopType: GameLoopType;
  lifecycle: {
    requiredStates: LifecycleState[];
    requiredTransitions: LifecycleTransition[];
    requiredUI: LifecycleUI[];
    requiredSignalsAnyOf: LifecycleSignal[];
    signal: LifecycleSignal;
    requiredControls: LifecycleControl[];
    startCondition: string;
    loseCondition: string;
    winCondition?: string;
    scoreRule: string;
  };
  mustHave: {
    hasEnemies: boolean;
    hasAI: boolean;
    hasScore: boolean;
    hasHUD: boolean;
    hasSpawner: boolean;
  };
}

export interface PlanDiff {
  autoAddedSystems: string[];
  autoAddedEntities: string[];
  coreLoopAutoGenerated: boolean;
  loopTypeAutoFixed: boolean;
  lifecycle: {
    autoAddedStates: string[];
    autoAddedTransitions: string[];
    autoAddedUI: string[];
    autoAddedControls: string[];
    requiredSignalsAnyOfAutoAdded: boolean;
    signalAutoChosen: boolean;
    startConditionAutoAdded: boolean;
    loseConditionAutoAdded: boolean;
    winConditionAutoAdded: boolean;
    scoreRuleAutoAdded: boolean;
  };
}

// Sistemas constitucionais obrigatórios (sempre necessários)
const CONSTITUTIONAL_SYSTEMS = [
  "GameStateSystem",  // FSM obrigatório
  "InputSystem",      // Input obrigatório
  "SaveSystem"        // Save obrigatório
] as const;

// Sistemas opcionais por gênero
const OPTIONAL_SYSTEMS = [
  "PhysicsSystem",
  "CollisionSystem",
  "ParticleSystem",
  "AnimationSystem",
  "AudioSystem",
  "CameraSystem",
  "AISystem",
  "SpawnerSystem",
  "ScoreSystem",
  "UISystem",
  "TimerSystem",
  "DialogueSystem",
  "InventorySystem"
] as const;

// Todos os sistemas permitidos (constitucionais + opcionais)
const ORDAX_ALLOWED_SYSTEMS = [...CONSTITUTIONAL_SYSTEMS, ...OPTIONAL_SYSTEMS] as const;

// Validar unicidade
const ALLOWED_SYSTEM_SET = new Set<string>(ORDAX_ALLOWED_SYSTEMS);
if (ALLOWED_SYSTEM_SET.size !== ORDAX_ALLOWED_SYSTEMS.length) {
  console.warn("[game-plan-validator] ⚠️ Sistemas duplicados detectados em ORDAX_ALLOWED_SYSTEMS");
}

function uniq(list: (string | null | undefined)[]): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  for (const s of list) {
    if (!isNonEmptyString(s) || seen.has(s)) continue;
    seen.add(s);
    out.push(s);
  }
  return out;
}

function containsAny(haystack: string, needles: (string | null | undefined)[]): boolean {
  if (!isNonEmptyString(haystack) || !Array.isArray(needles)) {
    return false;
  }
  const t = safeToLowerCase(haystack);
  return needles.some((n) => isNonEmptyString(n) && t.includes(safeToLowerCase(n)));
}

function requiredSystemsForGenre(gameType: OrdaxGameType): string[] {
  // Validate gameType
  const validatedGameType = validateOrdaxGameType(gameType);
  
  // Sistemas base do gênero
  const base = ["CameraSystem", "UISystem"];
  
  switch (validatedGameType) {
    case "puzzle":
      return [...CONSTITUTIONAL_SYSTEMS, ...base, "ScoreSystem", "TimerSystem"];
    case "racing":
    case "sports":
      return [...CONSTITUTIONAL_SYSTEMS, ...base, "PhysicsSystem", "CollisionSystem", "TimerSystem", "ScoreSystem"];
    case "platformer":
      return [...CONSTITUTIONAL_SYSTEMS, ...base, "PhysicsSystem", "CollisionSystem", "ScoreSystem"];
    case "topdown":
      return [...CONSTITUTIONAL_SYSTEMS, ...base, "PhysicsSystem", "CollisionSystem", "AISystem", "SpawnerSystem", "ScoreSystem", "TimerSystem"];
    case "shooter":
      return [...CONSTITUTIONAL_SYSTEMS, ...base, "PhysicsSystem", "CollisionSystem", "AISystem", "SpawnerSystem", "ScoreSystem", "TimerSystem"];
    default:
      // Fallback mais conservador: apenas sistemas constitucionais e base
      return [...CONSTITUTIONAL_SYSTEMS, ...base];
  }
}

function requiredEntitiesForGenre(gameType: OrdaxGameType): string[] {
  // Validate gameType
  const validatedGameType = validateOrdaxGameType(gameType);
  
  const base = ["player"];
  switch (validatedGameType) {
    case "platformer":
      return [...base, "spawner", "enemy", "pickup"];
    case "shooter":
      return [...base, "spawner", "enemy", "pickup"];
    case "topdown":
      return [...base, "spawner", "enemy", "pickup"];
    case "puzzle":
      return [...base, "pickup"];
    case "racing":
      return [...base, "goal", "pickup"];
    case "sports":
      return [...base, "goal", "pickup"];
    default:
      return [...base, "spawner", "enemy", "pickup"];
  }
}

function sanitizeEntities(entities: unknown): string[] {
  const list = validateArrayParam(entities, "entities", (e): e is string => typeof e === "string");
  const allowedSet = new Set<string>(ALLOWED_ENTITIES);
  return uniq(list
    .map((s) => safeTrim(safeToLowerCase(s)))
    .filter((s) => isNonEmptyString(s) && allowedSet.has(s)));
}

function sanitizeSystems(systems: unknown): string[] {
  const list = validateArrayParam(systems, "systems", (s): s is string => typeof s === "string");
  return uniq(list.filter((s) => isNonEmptyString(s) && ALLOWED_SYSTEM_SET.has(s)));
}

function detectLoopType(coreLoop: string): GameLoopType {
  const t = safeToLowerCase(coreLoop);
  if (containsAny(t, LOOP_TYPE_KEYWORDS.survival)) return "survival";
  if (containsAny(t, LOOP_TYPE_KEYWORDS.winlose)) return "winlose";
  return "objective";
}

// Configuração de mapeamento de palavras-chave para sistemas
const PROMPT_KEYWORD_MAPPINGS = [
  {
    keywords: ["diálogo", "dialogo", "npc", "conversa", "dialogue", "conversation", "talk"],
    system: "DialogueSystem",
    note: "Prompt menciona diálogo/NPC → exigir DialogueSystem"
  },
  {
    keywords: ["inventário", "inventario", "loot", "itens", "items", "inventory", "item"],
    system: "InventorySystem",
    note: "Prompt menciona inventário/itens → exigir InventorySystem"
  },
  {
    keywords: ["salvar", "save", "checkpoint", "saving", "checkpoints"],
    system: "SaveSystem",
    note: "Prompt menciona salvar/checkpoint → exigir SaveSystem"
  },
  {
    keywords: ["áudio", "audio", "som", "música", "musica", "sfx", "music", "sound", "audio"],
    system: "AudioSystem",
    note: "Prompt menciona áudio → exigir AudioSystem"
  },
  {
    keywords: ["partícula", "particula", "poeira", "explosão", "explosao", "fx", "particle", "explosion", "effects"],
    system: "ParticleSystem",
    note: "Prompt menciona efeitos/partículas → exigir ParticleSystem"
  }
] as const;

// Entidades permitidas
const ALLOWED_ENTITIES = ["player", "spawner", "enemy", "pickup", "goal"] as const;

// Textos localizáveis
const SCORE_RULES = {
  optional: "score opcional",
  platformerSurvival: "score = tempo sobrevivido + moedas",
  platformerDefault: "score = moedas + objetivos",
  shooterSurvival: "score = kills + tempo",
  shooterDefault: "score = kills + objetivos",
  topdownSurvival: "score = kills + tempo",
  topdownDefault: "score = objetivos + pickups",
  racing: "score = checkpoints/laps (tempo menor é melhor)",
  sports: "score = pontos da partida",
  puzzle: "score = objetivo concluído (tempo menor é melhor)",
  default: "score = objetivos + tempo"
} as const;

const TITLE_FALLBACKS = {
  racing: "Corrida Rápida",
  shooter: "Batalha Espacial",
  platformer: "Aventura de Plataforma",
  puzzle: "Desafio de Lógica",
  sports: "Competição Esportiva",
  topdown: "Batalha Top-Down",
  default: "Novo Jogo"
} as const;

const DESCRIPTION_FALLBACKS = {
  racing: "Um jogo de corrida emocionante onde você compete para chegar em primeiro lugar.",
  shooter: "Um jogo de tiro onde você enfrenta ondas de inimigos e sobrevive o máximo possível.",
  platformer: "Um jogo de plataforma onde você pula, coleta itens e derrota inimigos.",
  puzzle: "Um jogo de quebra-cabeça que desafia sua lógica e raciocínio.",
  sports: "Um jogo esportivo competitivo onde você testa suas habilidades.",
  topdown: "Um jogo top-down onde você controla seu personagem e enfrenta desafios.",
  default: "Um jogo criado com Ordax"
} as const;

// Palavras-chave para detecção de loop type
const LOOP_TYPE_KEYWORDS = {
  survival: ["sobreviver", "survive", "ondas", "wave", "tempo", "time", "survival", "waves", "time"],
  winlose: ["vencer", "vitória", "vitoria", "derrota", "perder", "ganhar", "win", "lose", "victory", "defeat", "winning", "losing"]
} as const;

function promptRequiredSystems(prompt: string): { systems: string[]; notes: string[] } {
  const notes: string[] = [];
  const systems: string[] = [];

  for (const mapping of PROMPT_KEYWORD_MAPPINGS) {
    if (containsAny(prompt, mapping.keywords)) {
      systems.push(mapping.system);
      notes.push(mapping.note);
    }
  }

  return { systems: uniq(systems), notes };
}

function pickDefaultSignal(loopType: GameLoopType, mustHave: GamePlan["mustHave"], requiredEntities: string[]): LifecycleSignal {
  const validatedLoopType = validateGameLoopType(loopType);
  if (mustHave.hasEnemies || requiredEntities.includes("enemy")) return "player_health";
  if (validatedLoopType === "objective") return "objective_progress";
  return "timer";
}

function defaultLoseCondition(gameType: OrdaxGameType, signal: LifecycleSignal, loopType: GameLoopType): string {
  const validatedSignal = validateLifecycleSignal(signal);
  
  // Baseado no signal
  if (validatedSignal === "player_health") return "player_health <= 0";
  if (validatedSignal === "objective_progress") return "objective_progress <= 0";
  
  // Fallback para timer
  return "timer <= 0";
}

function defaultWinCondition(loopType: GameLoopType, signal: LifecycleSignal, mustHave: GamePlan["mustHave"]): string {
  const validatedLoopType = validateGameLoopType(loopType);
  const validatedSignal = validateLifecycleSignal(signal);
  
  if (validatedLoopType === "survival") return "sobreviver o máximo possível";
  if (validatedSignal === "objective_progress") return "objective_progress >= 1";
  if (validatedLoopType === "winlose" && mustHave.hasScore) return "score >= 10";
  return "completar objetivo";
}

function defaultScoreRule(gameType: OrdaxGameType, loopType: GameLoopType, mustHave: GamePlan["mustHave"]): string {
  if (!mustHave.hasScore) return SCORE_RULES.optional;
  
  switch (gameType) {
    case "platformer":
      return loopType === "survival" ? SCORE_RULES.platformerSurvival : SCORE_RULES.platformerDefault;
    case "shooter":
      return loopType === "survival" ? SCORE_RULES.shooterSurvival : SCORE_RULES.shooterDefault;
    case "topdown":
      return loopType === "survival" ? SCORE_RULES.topdownSurvival : SCORE_RULES.topdownDefault;
    case "racing":
      return SCORE_RULES.racing;
    case "sports":
      return SCORE_RULES.sports;
    case "puzzle":
      return SCORE_RULES.puzzle;
    default:
      return SCORE_RULES.default;
  }
}

function normalizeLifecycle(input: unknown) {
  // Type-safe extraction without 'as any'
  const inputObj = input && typeof input === 'object' ? input as Record<string, unknown> : {};
  
  // Extract and validate arrays using type guards
  const states = filterValidLifecycleStates(Array.isArray(inputObj.requiredStates) ? inputObj.requiredStates : []);
  const transitions = filterValidLifecycleTransitions(Array.isArray(inputObj.requiredTransitions) ? inputObj.requiredTransitions : []);
  const ui = filterValidLifecycleUIs(Array.isArray(inputObj.requiredUI) ? inputObj.requiredUI : []);
  const controls = filterValidLifecycleControls(Array.isArray(inputObj.requiredControls) ? inputObj.requiredControls : []);
  const anyOf = filterValidLifecycleSignals(Array.isArray(inputObj.requiredSignalsAnyOf) ? inputObj.requiredSignalsAnyOf : []);

  // Validate single values
  const signal = isLifecycleSignal(inputObj.signal) ? inputObj.signal : undefined;
  const startCondition = validateStringParam(inputObj.startCondition, "startCondition", "");
  const loseCondition = validateStringParam(inputObj.loseCondition, "loseCondition", "");
  const winCondition = validateStringParam(inputObj.winCondition, "winCondition", "");
  const scoreRule = validateStringParam(inputObj.scoreRule, "scoreRule", "");

  return {
    states: uniq(states),
    transitions: uniq(transitions),
    ui: uniq(ui),
    controls: uniq(controls),
    requiredSignalsAnyOf: uniq(anyOf),
    signal,
    startCondition: startCondition || undefined,
    loseCondition: loseCondition || undefined,
    winCondition: winCondition || undefined,
    scoreRule: scoreRule || undefined,
  };
}

// Helper functions for validateAndCompletePlan
function validateInputAndExtractData(input: unknown, userPrompt: string) {
  const inputObj = input && typeof input === 'object' ? input as Record<string, unknown> : {};
  const gameType = validateOrdaxGameType(inputObj.gameType ?? "unknown");
  
  return {
    inputObj,
    gameType,
    userPrompt: validateStringParam(userPrompt, "userPrompt", "")
  };
}

function collectRequiredSystems(gameType: OrdaxGameType, userPrompt: string, inputObj: Record<string, unknown>) {
  const genreReq = requiredSystemsForGenre(gameType);
  const promptReq = promptRequiredSystems(userPrompt);
  const rawSystems = sanitizeSystems(inputObj.requiredSystems);
  
  return { genreReq, promptReq, rawSystems };
}

function collectRequiredEntities(gameType: OrdaxGameType, inputObj: Record<string, unknown>) {
  const genreEntities = requiredEntitiesForGenre(gameType);
  const rawEntities = sanitizeEntities(inputObj.requiredEntities);
  
  return { genreEntities, rawEntities };
}

function buildMustHave(gameType: OrdaxGameType, requiredSystems: string[]) {
  return {
    hasHUD: true,
    hasScore: requiredSystems.includes("ScoreSystem"),
    hasSpawner: requiredSystems.includes("SpawnerSystem"),
    hasAI: requiredSystems.includes("AISystem"),
    hasEnemies: gameType === "topdown" || gameType === "shooter" || gameType === "platformer" ? true : false,
  };
}

function buildLifecycleData(
  inputObj: Record<string, unknown>,
  loopType: GameLoopType,
  mustHave: ReturnType<typeof buildMustHave>,
  requiredEntities: string[],
  gameType: OrdaxGameType
) {
  const rawLifecycle = normalizeLifecycle(inputObj.lifecycle);
  const baseStates: LifecycleState[] = ["start", "playing", "gameover"];
  const baseTransitions: LifecycleTransition[] = ["start->playing", "playing->gameover", "gameover->restart"];
  const baseUI: LifecycleUI[] = ["hud", "gameover_screen"];
  const baseControls: LifecycleControl[] = ["start_game", "restart_game"];
  const baseSignalsAnyOf: LifecycleSignal[] = ["player_health", "objective_progress", "timer"];

  const states = uniq([...rawLifecycle.states, ...baseStates]) as LifecycleState[];
  const transitions = uniq([...rawLifecycle.transitions, ...baseTransitions]) as LifecycleTransition[];
  const ui = uniq([...rawLifecycle.ui, ...baseUI]) as LifecycleUI[];
  const controls = uniq([...rawLifecycle.controls, ...baseControls]) as LifecycleControl[];
  const requiredSignalsAnyOf = uniq([...rawLifecycle.requiredSignalsAnyOf, ...baseSignalsAnyOf]) as LifecycleSignal[];

  const computedSignal = rawLifecycle.signal ?? pickDefaultSignal(loopType, mustHave, requiredEntities);
  const startCondition = rawLifecycle.startCondition ?? "Jogador clica em 'Iniciar'";
  const loseCondition = rawLifecycle.loseCondition ?? defaultLoseCondition(gameType, computedSignal, loopType);
  const winCondition = rawLifecycle.winCondition ?? defaultWinCondition(loopType, computedSignal, mustHave);
  const scoreRule = rawLifecycle.scoreRule ?? defaultScoreRule(gameType, loopType, mustHave);

  return {
    rawLifecycle,
    states,
    transitions,
    ui,
    controls,
    requiredSignalsAnyOf,
    computedSignal,
    startCondition,
    loseCondition,
    winCondition,
    scoreRule
  };
}

function buildPlanDiff(
  rawSystems: string[],
  requiredSystems: string[],
  rawEntities: string[],
  requiredEntities: string[],
  inputObj: Record<string, unknown>,
  rawLifecycle: ReturnType<typeof normalizeLifecycle>,
  states: LifecycleState[],
  transitions: LifecycleTransition[],
  ui: LifecycleUI[],
  controls: LifecycleControl[]
): PlanDiff {
  const lifecycleObj = inputObj.lifecycle && typeof inputObj.lifecycle === 'object' ? inputObj.lifecycle as Record<string, unknown> : {};
  
  return {
    autoAddedSystems: requiredSystems.filter((s) => !rawSystems.includes(s)),
    autoAddedEntities: requiredEntities.filter((e) => !rawEntities.includes(e)),
    coreLoopAutoGenerated: !inputObj.coreLoop,
    loopTypeAutoFixed: !inputObj.loopType,
    lifecycle: {
      autoAddedStates: states.filter((s) => !rawLifecycle.states.includes(s)),
      autoAddedTransitions: transitions.filter((t) => !rawLifecycle.transitions.includes(t)),
      autoAddedUI: ui.filter((u) => !rawLifecycle.ui.includes(u)),
      autoAddedControls: controls.filter((c) => !rawLifecycle.controls.includes(c)),
      requiredSignalsAnyOfAutoAdded: !lifecycleObj.requiredSignalsAnyOf,
      signalAutoChosen: !rawLifecycle.signal,
      startConditionAutoAdded: !rawLifecycle.startCondition,
      loseConditionAutoAdded: !rawLifecycle.loseCondition,
      winConditionAutoAdded: !rawLifecycle.winCondition,
      scoreRuleAutoAdded: !rawLifecycle.scoreRule,
    },
  };
}

export function validateAndCompletePlan(
  input: unknown,
  userPrompt: string
): { plan: GamePlan; warnings: string[]; diff: PlanDiff } {
  const warnings: string[] = [];
  
  // Step 1: Validate input and extract data
  const { inputObj, gameType, userPrompt: validatedPrompt } = validateInputAndExtractData(input, userPrompt);
  
  // Step 2: Collect required systems
  const { genreReq, promptReq, rawSystems } = collectRequiredSystems(gameType, validatedPrompt, inputObj);
  
  // Step 3: Collect required entities
  const { genreEntities, rawEntities } = collectRequiredEntities(gameType, inputObj);
  
  // Step 4: Build required systems and entities with validation
  let requiredEntities = uniq([...rawEntities, ...genreEntities]);
  let requiredSystems = uniq([...rawSystems, ...genreReq, ...promptReq.systems]);

  // Add missing required systems with warnings
  for (const s of genreReq) {
    if (!requiredSystems.includes(s)) {
      requiredSystems.push(s);
      warnings.push(`Plano incompleto: adicionado system obrigatório do gênero: ${s}`);
    }
  }
  for (const s of promptReq.systems) {
    if (!requiredSystems.includes(s)) {
      requiredSystems.push(s);
      warnings.push(`Plano incompleto: adicionado system exigido pelo prompt: ${s}`);
    }
  }

  // Step 5: Build mustHave object
  const mustHave = buildMustHave(gameType, requiredSystems);

  // Add AI and Spawner systems if enemies are required
  if (mustHave.hasEnemies && !requiredSystems.includes("AISystem")) {
    requiredSystems.push("AISystem");
    warnings.push("Gênero exige inimigos: adicionado AISystem");
  }
  if (mustHave.hasEnemies && !requiredSystems.includes("SpawnerSystem")) {
    requiredSystems.push("SpawnerSystem");
    warnings.push("Gênero exige inimigos: adicionado SpawnerSystem");
  }

  // Step 6: Determine core loop and loop type
  const coreLoop = validateStringParam(inputObj.coreLoop, "coreLoop", "Jogador controla personagem e completa objetivos");
  const loopType = detectLoopType(coreLoop);

  // Step 7: Build lifecycle data
  const lifecycleData = buildLifecycleData(inputObj, loopType, mustHave, requiredEntities, gameType);

  // Step 8: Build fallbacks específicos por gameType
  const titleFallback = TITLE_FALLBACKS[gameType] || TITLE_FALLBACKS.default;
  const descriptionFallback = DESCRIPTION_FALLBACKS[gameType] || DESCRIPTION_FALLBACKS.default;

  // Step 9: Build final plan
  const plan: GamePlan = {
    kind: "GAME_PLAN",
    gameType,
    title: validateStringParam(inputObj.title, "title", titleFallback),
    description: validateStringParam(inputObj.description, "description", descriptionFallback),
    coreLoop,
    requiredSystems,
    requiredEntities,
    loopType,
    lifecycle: {
      requiredStates: lifecycleData.states,
      requiredTransitions: lifecycleData.transitions,
      requiredUI: lifecycleData.ui,
      requiredSignalsAnyOf: lifecycleData.requiredSignalsAnyOf,
      signal: lifecycleData.computedSignal,
      requiredControls: lifecycleData.controls,
      startCondition: lifecycleData.startCondition,
      loseCondition: lifecycleData.loseCondition,
      winCondition: lifecycleData.winCondition,
      scoreRule: lifecycleData.scoreRule,
    },
    mustHave,
  };

  // Step 10: Build diff
  const diff = buildPlanDiff(
    rawSystems,
    requiredSystems,
    rawEntities,
    requiredEntities,
    inputObj,
    lifecycleData.rawLifecycle,
    lifecycleData.states,
    lifecycleData.transitions,
    lifecycleData.ui,
    lifecycleData.controls
  );

  return { plan, warnings, diff };
}
