// Auto-generated by lovable-exec - DO NOT EDIT
import { defineConfig } from "vite";
import baseConfig from "../vite.config.ts";

import { componentTagger } from "lovable-tagger";

const userConfig = baseConfig;
const lovableTagger = componentTagger();

export default defineConfig(async (configEnv) => {
  const resolvedConfig =
    typeof userConfig === "function" ? await userConfig(configEnv) : userConfig;
  const rawPlugins = resolvedConfig?.plugins;
  const plugins = Array.isArray(rawPlugins) ? rawPlugins : rawPlugins ? [rawPlugins] : [];
  const existingPlugins = plugins.filter((p) => p?.name !== "lovable-tagger");
  return {
    ...resolvedConfig,
    plugins: [...existingPlugins, lovableTagger],
  };
});
