/**
 * Mock Data
 * 
 * Dados de exemplo para desenvolvimento e fallback
 */

import {
  Utensils, ShoppingBag, Heart, GraduationCap, Wrench, Store,
  Star, Users, ThumbsUp, Navigation,
  MapPin, TrendingUp,
} from "lucide-react";
import type { Category, Business, NeighborActivity, Stat, QuickFilter, Benefit } from "../sections/types";

// ── Categorias ───────────────────────────────────────────────────────
export const CATEGORIES: readonly Category[] = [
  { icon: Utensils, label: "Restaurantes", count: "124", iconColor: "text-orange-400", bg: "bg-orange-500/15 border-orange-500/20", slug: "restaurantes" },
  { icon: ShoppingBag, label: "Mercados", count: "67", iconColor: "text-emerald-400", bg: "bg-emerald-500/15 border-emerald-500/20", slug: "mercados" },
  { icon: Heart, label: "Saúde", count: "89", iconColor: "text-rose-400", bg: "bg-rose-500/15 border-rose-500/20", slug: "saude" },
  { icon: GraduationCap, label: "Educação", count: "45", iconColor: "text-sky-400", bg: "bg-sky-500/15 border-sky-500/20", slug: "educacao" },
  { icon: Wrench, label: "Serviços", count: "156", iconColor: "text-amber-400", bg: "bg-amber-500/15 border-amber-500/20", slug: "servicos" },
  { icon: Store, label: "Lojas", count: "203", iconColor: "text-violet-400", bg: "bg-violet-500/15 border-violet-500/20", slug: "outros" },
] as const;

// ── Empresas com dados comunitários ──────────────────────────────────
export const FEATURED_BUSINESSES: readonly Business[] = [
  {
    id: "sabor-da-bahia", 
    slug: "sabor-da-bahia",
    geographic_path: "/br/ba/salvador/pituba",
    name: "Sabor da Bahia", 
    category: "Restaurante",
    subcategoria: "Culinária Baiana",
    rating: 4.8, 
    reviews: 234, 
    distance: "350m", 
    walkTime: "5 min",
    description: "Comida baiana autêntica com ingredientes frescos do mercado local.",
    tags: ["Delivery", "Presencial"], 
    premium: true, 
    isOpen: true,
    neighborRecs: 47, 
    lastVisit: "Maria recomendou há 2h",
    coords: { lat: -12.975, lng: -38.476 },
    phone: "(71) 3333-4444",
    whatsapp: "5571999998888",
    email: "contato@sabordabahia.com.br",
    website: "https://sabordabahia.com.br",
    is_premium: true,
    is_verified: true,
    horario_funcionamento: {
      segunda: { open: "11:00", close: "22:00" },
      terca: { open: "11:00", close: "22:00" },
      quarta: { open: "11:00", close: "22:00" },
      quinta: { open: "11:00", close: "22:00" },
      sexta: { open: "11:00", close: "23:00" },
      sabado: { open: "11:00", close: "23:00" },
      domingo: { open: "12:00", close: "21:00" },
    },
    formas_pagamento: ["PIX", "Cartão de Crédito", "Cartão de Débito", "Dinheiro"],
    especialidades: ["Moqueca de Camarão", "Acarajé", "Vatapá"],
    facilidades: ["estacionamento", "acessibilidade", "wifi"],
    modos_atendimento: ["presencial", "delivery"],
  },
  {
    id: "farmacia-saude-plus",
    slug: "farmacia-saude-plus",
    geographic_path: "/br/ba/salvador/pituba",
    name: "Farmácia Saúde+", 
    category: "Farmácia",
    rating: 4.6, 
    reviews: 189, 
    distance: "120m", 
    walkTime: "2 min",
    description: "Medicamentos, higiene pessoal e atendimento farmacêutico 24h.",
    tags: ["Delivery", "24h"], 
    premium: false, 
    isOpen: true,
    neighborRecs: 89, 
    lastVisit: "João visitou ontem",
    coords: { lat: -12.974, lng: -38.477 },
    phone: "(71) 3222-5555",
    whatsapp: "5571988887777",
    email: "atendimento@farmaciasaudemais.com.br",
    is_premium: false,
    is_verified: true,
    horario_funcionamento: {
      segunda: { open: "00:00", close: "23:59" },
      terca: { open: "00:00", close: "23:59" },
      quarta: { open: "00:00", close: "23:59" },
      quinta: { open: "00:00", close: "23:59" },
      sexta: { open: "00:00", close: "23:59" },
      sabado: { open: "00:00", close: "23:59" },
      domingo: { open: "00:00", close: "23:59" },
    },
    formas_pagamento: ["PIX", "Cartão de Crédito", "Cartão de Débito", "Dinheiro"],
    especialidades: ["Manipulação", "Dermocosméticos", "Homeopatia"],
    facilidades: ["estacionamento", "acessibilidade"],
    modos_atendimento: ["presencial", "delivery"],
  },
  {
    id: "auto-center-nordeste",
    slug: "auto-center-nordeste",
    geographic_path: "/br/ba/salvador/pituba",
    name: "Auto Center Nordeste", 
    category: "Serviços",
    rating: 4.9, 
    reviews: 312, 
    distance: "800m", 
    walkTime: "12 min",
    description: "Mecânica geral, troca de óleo e alinhamento com preço justo.",
    tags: ["Presencial"], 
    premium: true, 
    isOpen: false,
    neighborRecs: 156, 
    lastVisit: "Carlos avaliou com 5★ há 1 dia",
    coords: { lat: -12.976, lng: -38.475 },
    phone: "(71) 99999-9012",
    is_premium: true,
    is_verified: true,
    horario_funcionamento: {
      segunda: { open: "08:00", close: "18:00" },
      terca: { open: "08:00", close: "18:00" },
      quarta: { open: "08:00", close: "18:00" },
      quinta: { open: "08:00", close: "18:00" },
      sexta: { open: "08:00", close: "18:00" },
      sabado: { open: "08:00", close: "12:00" },
      domingo: { closed: true },
    },
    formas_pagamento: ["PIX", "Cartão de Crédito", "Dinheiro"],
    especialidades: ["Mecânica Geral", "Troca de Óleo", "Alinhamento"],
    facilidades: ["estacionamento"],
    modos_atendimento: ["presencial"],
  },
  {
    id: "mercadinho-familia",
    slug: "mercadinho-familia",
    geographic_path: "/br/ba/salvador/pituba",
    name: "Mercadinho Família", 
    category: "Mercado",
    rating: 4.5, 
    reviews: 156, 
    distance: "200m", 
    walkTime: "3 min",
    description: "Produtos frescos, hortifrúti e itens essenciais do dia a dia.",
    tags: ["Delivery", "Presencial"], 
    premium: false, 
    isOpen: true,
    neighborRecs: 203, 
    lastVisit: "Ana comprou hoje",
    coords: { lat: -12.973, lng: -38.478 },
    phone: "(71) 99999-3456",
    is_premium: false,
    is_verified: true,
    horario_funcionamento: {
      segunda: { open: "07:00", close: "20:00" },
      terca: { open: "07:00", close: "20:00" },
      quarta: { open: "07:00", close: "20:00" },
      quinta: { open: "07:00", close: "20:00" },
      sexta: { open: "07:00", close: "20:00" },
      sabado: { open: "07:00", close: "18:00" },
      domingo: { open: "08:00", close: "13:00" },
    },
    formas_pagamento: ["PIX", "Cartão de Crédito", "Dinheiro"],
    especialidades: ["Hortifrúti", "Produtos Frescos", "Mercearia"],
    facilidades: ["estacionamento"],
    modos_atendimento: ["presencial", "delivery"],
  },
  {
    id: "salao-beleza-rosa",
    slug: "salao-beleza-rosa",
    geographic_path: "/br/ba/salvador/pituba",
    name: "Salão Beleza Rosa", 
    category: "Beleza",
    rating: 4.7, 
    reviews: 98, 
    distance: "450m", 
    walkTime: "7 min",
    description: "Cortes, coloração, unhas e tratamentos capilares com agendamento online.",
    tags: ["Agendamento"], 
    premium: false, 
    isOpen: true,
    neighborRecs: 34, 
    lastVisit: "Luísa agendou ontem",
    coords: { lat: -12.977, lng: -38.474 },
    phone: "(71) 99999-7890",
    is_premium: false,
    is_verified: true,
    horario_funcionamento: {
      segunda: { closed: true },
      terca: { open: "09:00", close: "19:00" },
      quarta: { open: "09:00", close: "19:00" },
      quinta: { open: "09:00", close: "19:00" },
      sexta: { open: "09:00", close: "20:00" },
      sabado: { open: "09:00", close: "17:00" },
      domingo: { closed: true },
    },
    formas_pagamento: ["PIX", "Cartão de Crédito", "Dinheiro"],
    especialidades: ["Cortes", "Coloração", "Manicure"],
    facilidades: ["acessibilidade"],
    modos_atendimento: ["presencial"],
  },
  {
    id: "padaria-pao-quente",
    slug: "padaria-pao-quente",
    geographic_path: "/br/ba/salvador/pituba",
    name: "Padaria Pão Quente", 
    category: "Padaria",
    rating: 4.9, 
    reviews: 412, 
    distance: "90m", 
    walkTime: "1 min",
    description: "Pães artesanais, bolos e café fresquinho desde às 5h da manhã.",
    tags: ["Presencial"], 
    premium: true, 
    isOpen: true,
    neighborRecs: 312, 
    lastVisit: "15 vizinhos compraram hoje",
    coords: { lat: -12.974, lng: -38.476 },
    phone: "(71) 99999-2345",
    is_premium: true,
    is_verified: true,
    horario_funcionamento: {
      segunda: { open: "05:00", close: "20:00" },
      terca: { open: "05:00", close: "20:00" },
      quarta: { open: "05:00", close: "20:00" },
      quinta: { open: "05:00", close: "20:00" },
      sexta: { open: "05:00", close: "20:00" },
      sabado: { open: "05:00", close: "20:00" },
      domingo: { open: "06:00", close: "14:00" },
    },
    formas_pagamento: ["PIX", "Cartão de Crédito", "Dinheiro"],
    especialidades: ["Pães Artesanais", "Bolos", "Café"],
    facilidades: ["wifi"],
    modos_atendimento: ["presencial"],
  },
] as const;

// ── Atividade recente dos vizinhos ───────────────────────────────────
export const NEIGHBOR_ACTIVITY: readonly NeighborActivity[] = [
  { user: "Maria S.", action: "recomendou", business: "Sabor da Bahia", time: "2h atrás", emoji: "👍" },
  { user: "João P.", action: "visitou", business: "Farmácia Saúde+", time: "3h atrás", emoji: "📍" },
  { user: "Ana L.", action: "avaliou com 5★", business: "Padaria Pão Quente", time: "5h atrás", emoji: "⭐" },
  { user: "Carlos M.", action: "pediu delivery de", business: "Mercadinho Família", time: "6h atrás", emoji: "🛵" },
  { user: "Luísa R.", action: "agendou no", business: "Salão Beleza Rosa", time: "1 dia", emoji: "💇" },
] as const;

// ── Stats ────────────────────────────────────────────────────────────
export const STATS: readonly Stat[] = [
  { icon: Store, value: "850+", label: "empresas cadastradas" },
  { icon: Star, value: "4.7", label: "avaliação média" },
  { icon: Users, value: "15k+", label: "clientes ativos" },
  { icon: ThumbsUp, value: "2.3k", label: "recomendações de vizinhos" },
] as const;

// ── Quick Filters ────────────────────────────────────────────────────
export const QUICK_FILTERS: readonly QuickFilter[] = [
  { label: "Perto de mim", icon: Navigation, active: false },
  { label: "Abertos agora", icon: Store, active: false },
  { label: "Com delivery", icon: ShoppingBag, active: false },
  { label: "Recomendados", icon: ThumbsUp, active: false },
  { label: "Verificados", icon: Star, active: false },
] as const;

// ── Benefits ─────────────────────────────────────────────────────────
export const BENEFITS: readonly Benefit[] = [
  { 
    icon: MapPin, 
    title: "Visibilidade Local", 
    description: "Apareça para clientes do seu bairro", 
    iconClass: "text-primary", 
    bgClass: "bg-primary/10" 
  },
  { 
    icon: Star, 
    title: "Avaliações", 
    description: "Receba feedback e construa reputação", 
    iconClass: "text-warning", 
    bgClass: "bg-warning/10" 
  },
  { 
    icon: TrendingUp, 
    title: "Analytics", 
    description: "Acompanhe visitas e engajamento", 
    iconClass: "text-accent", 
    bgClass: "bg-accent/10" 
  },
] as const;
