import {
  Heart,
  HelpCircle,
  BarChart3,
  Calendar,
  Search,
  Bell,
  Users,
  Gift,
} from "lucide-react";

export const POST_TYPES = {
  discussao: {
    label: "Discussão",
    icon: Heart,
    color: "#3B82F6",
    category: "Social",
    description: "Debater temas do bairro",
  },
  pergunta: {
    label: "Pergunta",
    icon: HelpCircle,
    color: "#F59E0B",
    category: "Social",
    description: "Tirar dúvidas rápidas",
  },
  enquete: {
    label: "Enquete",
    icon: BarChart3,
    color: "#8B5CF6",
    category: "Social",
    description: "Votar em decisões",
  },
  evento: {
    label: "Evento",
    icon: Calendar,
    color: "#EC4899",
    category: "Social",
    description: "Marcar encontros e babas",
  },
  achados: {
    label: "Achados",
    icon: Search,
    color: "#06B6D4",
    category: "Utilidade",
    description: "Devolver itens perdidos",
  },
  alerta: {
    label: "Alerta",
    icon: Bell,
    color: "#EF4444",
    category: "Utilidade",
    description: "Avisos críticos",
  },
  favor: {
    label: "Favor",
    icon: Users,
    color: "#84CC16",
    category: "Ajuda/Trocas",
    description: "Pedir emprestado",
  },
  desapego: {
    label: "Desapego",
    icon: Gift,
    color: "#F97316",
    category: "Ajuda/Trocas",
    description: "Doar ou vender",
  },
  recomendacao: {
    label: "Recomendação",
    icon: Heart,
    color: "#10B981",
    category: "Ajuda/Trocas",
    description: "Indicar serviços",
  },
} as const;
