export const POST_LIMITS = {
  MIN_CONTENT_LENGTH: 10,
  MAX_CONTENT_LENGTH: 5000,
  MAX_IMAGES: 4,
  MAX_TAGS: 5,
  MAX_TAG_LENGTH: 30,
  MAX_DISTRIBUTION_CHANNELS: 8,
  MAX_DISTRIBUTION_CHANNEL_LENGTH: 40,
  MAX_CONTENT_INTENT_LENGTH: 64,
  MAX_DISPLAY_FORMAT_LENGTH: 64,
  MAX_CONTENT_PAYLOAD_BYTES: 16_384,
} as const;

export const COMMENT_LIMITS = {
  MIN_CONTENT_LENGTH: 1,
  MAX_CONTENT_LENGTH: 2000,
} as const;

export const SOCIAL_WRITE_LIMITS = {
  POSTS_PER_DAY: 5,
  COMMENTS_PER_HOUR: 10,
  GROUP_MESSAGES_PER_MINUTE: 30,
  POST_IMAGE_UPLOADS_PER_DAY: 20,
  POST_IMAGE_OBJECTS_PER_PROFILE: 200,
} as const;
