/**
 * Mock Data - Dados de exemplo para desenvolvimento
 * 
 * SSOT: Dados centralizados para testes e desenvolvimento
 * Sem gambiarras: Dados tipados e organizados
 */

import type { BusinessExtended, Product, Review, NearbyBusiness } from "../sections/types";

export const MOCK_BUSINESSES: Record<string, BusinessExtended> = {
  "sabor-da-bahia": {
    id: "sabor-da-bahia",
    profile_id: "sabor-da-bahia",
    name: "Sabor da Bahia",
    description: "Comida baiana autêntica com ingredientes frescos do mercado local. Especialidade em moqueca, acarajé e pratos típicos da culinária nordestina. Ambiente familiar e acolhedor no coração do bairro, servindo a comunidade há mais de 8 anos.",
    category: "restaurante",
    subcategoria: "Culinária Baiana",
    phone: "(71) 3333-4444",
    whatsapp: "5571999998888",
    email: "contato@sabordabahia.com.br",
    website: "https://sabordabahia.com.br",
    location_id: "salvador-pituba",
    location: {
      name: "Pituba",
      full_name: "Pituba, Salvador - BA",
      geographic_path: "/br/ba/salvador/pituba",
    },
    address: {
      street: "Rua das Palmeiras",
      number: "123",
      complement: "Loja A",
      postal_code: "41810-001",
      latitude: -12.975,
      longitude: -38.476,
    },
    geographic_path: "/br/ba/salvador/pituba",
    horario_funcionamento: {
      segunda: { open: "11:00", close: "22:00" },
      terca: { open: "11:00", close: "22:00" },
      quarta: { open: "11:00", close: "22:00" },
      quinta: { open: "11:00", close: "22:00" },
      sexta: { open: "11:00", close: "23:00" },
      sabado: { open: "11:00", close: "23:00" },
      domingo: { open: "12:00", close: "21:00" },
    },
    tem_delivery: true,
    aceita_cartao: true,
    aceita_pix: true,
    status: "active",
    rating: 4.8,
    total_reviews: 234,
    total_products: 12,
    is_premium: true,
    is_verified: true,
    is_featured: true,
    slug: "sabor-da-bahia",
    formas_pagamento: ["PIX", "Cartão de Crédito", "Cartão de Débito", "Dinheiro", "Vale Refeição"],
    especialidades: ["Moqueca de Camarão", "Acarajé", "Vatapá", "Caruru", "Bobó de Camarão"],
    facilidades: ["estacionamento", "acessibilidade", "wifi", "kids", "pet_friendly"],
    modos_atendimento: ["presencial", "delivery"],
    instagram: "sabordabahia",
    facebook: "sabordabahia",
    created_at: "2018-01-15T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    logo_url: null,
    banner_url: null,
    fotos: [],
  },
  "farmacia-saude-plus": {
    id: "farmacia-saude-plus",
    profile_id: "farmacia-saude-plus",
    name: "Farmácia Saúde+",
    description: "Medicamentos, higiene pessoal e atendimento farmacêutico 24h. Equipe especializada para orientação sobre medicamentos e saúde preventiva. Entrega rápida para todo o bairro.",
    category: "farmacia",
    phone: "(71) 3222-5555",
    whatsapp: "5571988887777",
    email: "atendimento@farmaciasaudemais.com.br",
    location_id: "salvador-pituba",
    location: {
      name: "Pituba",
      full_name: "Pituba, Salvador - BA",
      geographic_path: "/br/ba/salvador/pituba",
    },
    address: {
      street: "Av. Tancredo Neves",
      number: "450",
      postal_code: "41820-020",
    },
    geographic_path: "/br/ba/salvador/pituba",
    tem_delivery: true,
    aceita_cartao: true,
    aceita_pix: true,
    status: "active",
    rating: 4.6,
    total_reviews: 189,
    total_products: 0,
    is_premium: false,
    is_verified: true,
    slug: "farmacia-saude-plus",
    formas_pagamento: ["PIX", "Cartão de Crédito", "Cartão de Débito", "Dinheiro"],
    especialidades: ["Manipulação", "Dermocosméticos", "Homeopatia"],
    facilidades: ["estacionamento", "acessibilidade"],
    modos_atendimento: ["presencial", "delivery"],
    created_at: "2020-02-10T00:00:00Z",
    updated_at: "2026-02-15T00:00:00Z",
    logo_url: null,
    banner_url: null,
    fotos: [],
  },
};

export const MOCK_PRODUCTS: readonly Product[] = [
  {
    id: "1",
    name: "Moqueca de Camarão",
    description: "Receita tradicional baiana com leite de coco e dendê",
    price: 59.90,
    promotional_price: 49.90,
    category: "Pratos Principais",
    image_url: null,
    featured: true,
    active: true,
  },
  {
    id: "2",
    name: "Acarajé Completo",
    description: "Com vatapá, caruru, camarão e salada",
    price: 18.00,
    category: "Lanches",
    image_url: null,
    featured: true,
    active: true,
  },
  {
    id: "3",
    name: "Bobó de Camarão",
    description: "Creme de mandioca com camarões frescos",
    price: 54.90,
    category: "Pratos Principais",
    image_url: null,
    featured: false,
    active: true,
  },
  {
    id: "4",
    name: "Vatapá",
    description: "Feito com pão, camarão seco e amendoim",
    price: 32.00,
    category: "Porções",
    image_url: null,
    featured: false,
    active: true,
  },
  {
    id: "5",
    name: "Suco de Maracujá",
    description: "Natural, sem açúcar",
    price: 10.00,
    category: "Bebidas",
    image_url: null,
    featured: false,
    active: true,
  },
  {
    id: "6",
    name: "Cocada Baiana",
    description: "Doce artesanal de coco",
    price: 8.00,
    promotional_price: 6.50,
    category: "Sobremesas",
    image_url: null,
    featured: true,
    active: true,
  },
];

export const MOCK_REVIEWS: readonly Review[] = [
  {
    id: "1",
    user_name: "Maria Silva",
    rating: 5,
    comment: "Excelente atendimento! Recomendo muito. A equipe é super atenciosa e a comida é maravilhosa.",
    created_at: "2026-03-15",
    isNeighbor: true,
    avatar: null,
  },
  {
    id: "2",
    user_name: "João Santos",
    rating: 4,
    comment: "Ótima experiência, bom custo-benefício. Voltarei com certeza!",
    created_at: "2026-03-10",
    isNeighbor: true,
    avatar: null,
  },
  {
    id: "3",
    user_name: "Ana Costa",
    rating: 5,
    comment: "Lugar incrível! Preço justo e atendimento impecável. A moqueca é a melhor do bairro.",
    created_at: "2026-02-28",
    isNeighbor: false,
    avatar: null,
  },
  {
    id: "4",
    user_name: "Carlos Mendes",
    rating: 5,
    comment: "Frequento há anos. Nunca decepciona. Delivery sempre pontual.",
    created_at: "2026-02-20",
    isNeighbor: true,
    avatar: null,
  },
];

export const NEARBY_BUSINESSES: readonly NearbyBusiness[] = [
  {
    id: "farmacia-saude-plus",
    name: "Farmácia Saúde+",
    category: "Farmácia",
    distance: "120m",
    rating: 4.6,
    isOpen: true,
  },
  {
    id: "padaria-pao-quente",
    name: "Padaria Pão Quente",
    category: "Padaria",
    distance: "90m",
    rating: 4.9,
    isOpen: true,
  },
  {
    id: "mercadinho-familia",
    name: "Mercadinho Família",
    category: "Mercado",
    distance: "200m",
    rating: 4.5,
    isOpen: true,
  },
  {
    id: "salao-beleza-rosa",
    name: "Salão Beleza Rosa",
    category: "Beleza",
    distance: "450m",
    rating: 4.7,
    isOpen: false,
  },
];

export const AREAS_ATENDIDAS: readonly string[] = [
  "Pituba",
  "Itaigara",
  "Caminho das Árvores",
  "Iguatemi",
  "Nordeste de Amaralina",
  "Santa Cruz",
  "Vale das Pedrinhas",
];
